# Generated by Django 6.0.2 on 2026-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок объявления')),
                ('price', models.IntegerField(verbose_name='Цена ($)')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Квартира'), ('VILLA', 'Вилла'), ('OFFICE', 'Офис'), ('LAND', 'Земельный участок')], max_length=20, verbose_name='Тип недвижимости')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('sq_meters', models.IntegerField(verbose_name='Площадь (м²)')),
                ('bedrooms', models.IntegerField(verbose_name='Количество спален')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Есть бассейн?')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('list_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
    ]
